spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
    username: '***'
    password: '***'
dubbo:
  application:
    qos-enable: true
    name: MicroServiceApplication
    qos-port: 22222
    qos-accept-foreign-ip: false
    logger: slf4j
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: tri
    port: 50051
server:
  port: 8080
management:
  metrics:
    enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      base-path: /
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  server:
    port: 7002
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.chenjiacheng.micro.micro.service.entity
